# Generated by Django 5.2.14 on 2026-05-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contact_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_email_source',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='lead',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, help_text="Date de demande d'opposition (RGPD art 21) — exclu de tout envoi futur", null=True),
        ),
    ]
