# Generated by Django 5.2.14 on 2026-06-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_deal_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='outcome',
            field=models.CharField(blank=True, choices=[('converted', 'Converted'), ('not_interested', 'Not Interested'), ('wrong_fit', 'Wrong Fit'), ('no_budget', 'No Budget'), ('has_solution', 'Has Solution'), ('bad_timing', 'Bad Timing'), ('unresponsive', 'Unresponsive'), ('pre_existing_relation', 'Pre Existing Relation'), ('duplicate_campaign', 'Duplicate Campaign'), ('unknown', 'Unknown')], default='', max_length=30),
        ),
    ]
