# Generated by Django 5.2.14 on 2026-06-18 12:01
# + data-migration Lot 2 RGPD : chiffrement at-rest de la clé API + purge des
#   mots de passe LinkedIn en clair (plus utilisés depuis la refonte 11/06).

import ekoalu.crypto
from django.db import migrations, models


def encrypt_existing_secrets(apps, schema_editor):
    """Chiffre la clé API déjà en base (re-save → EncryptedCharField.get_prep_value)
    et blanchit tout mot de passe LinkedIn stocké en clair."""
    SiteConfig = apps.get_model("linkedin", "SiteConfig")
    for cfg in SiteConfig.objects.all():
        # from_db_value a déjà déchiffré (no-op sur du clair legacy) ; le save
        # re-prépare la valeur → chiffrée si EKOALU_FIELD_ENCRYPTION_KEY est posée.
        if cfg.llm_api_key:
            cfg.save(update_fields=["llm_api_key"])

    LinkedInProfile = apps.get_model("linkedin", "LinkedInProfile")
    LinkedInProfile.objects.exclude(linkedin_password="").update(linkedin_password="")


def noop_reverse(apps, schema_editor):
    """Pas de déchiffrement inverse (la clé reste dans l'env ; on ne re-stocke
    jamais en clair). Le mot de passe purgé n'est pas restaurable (il était mort)."""


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0008_campaign_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinprofile',
            name='linkedin_password',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='llm_api_key',
            field=ekoalu.crypto.EncryptedCharField(blank=True, default='', max_length=1000),
        ),
        migrations.RunPython(encrypt_existing_secrets, noop_reverse),
    ]
