# Generated by Django 5.2.14 on 2026-05-11 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_public_id', models.CharField(db_index=True, max_length=128)),
                ('campaign_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('inbound_message', models.TextField(help_text='Message du prospect')),
                ('intent', models.CharField(choices=[('rdv_request', 'RDV_REQUEST'), ('technical_question', 'TECHNICAL_QUESTION'), ('objection', 'OBJECTION'), ('off_topic', 'OFF_TOPIC'), ('opt_out', 'OPT_OUT')], default='off_topic', max_length=32)),
                ('ai_draft', models.TextField(help_text='Brouillon généré par Claude')),
                ('final_sent', models.TextField(blank=True, help_text='Texte final envoyé (après édition Richard)')),
                ('status', models.CharField(choices=[('pending', 'En attente validation'), ('sent', 'Envoyé'), ('discarded', 'Abandonné')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='ekoalu_pend_status_cff53a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CorrectionExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_slug', models.CharField(db_index=True, max_length=64)),
                ('similarity_ratio', models.FloatField(help_text='0.0 = totalement réécrit, 1.0 = aucune correction')),
                ('diff_lines', models.JSONField(default=list, help_text='Liste de lignes diff unifiées (debug)')),
                ('used_in_prompt', models.BooleanField(db_index=True, default=False, help_text='True quand l exemple a été injecté en few-shot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pending_reply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='ekoalu.pendingreply')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
