# Generated by Django 5.2.14 on 2026-05-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_public_id', models.CharField(db_index=True, max_length=128)),
                ('prospect_urn', models.CharField(blank=True, max_length=128)),
                ('campaign_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('invitation', 'Invitation LinkedIn'), ('follow_up', 'Message follow-up'), ('reply', 'Réponse à un prospect')], db_index=True, max_length=16)),
                ('ai_draft', models.TextField(help_text="Message généré par l'IA (Claude)")),
                ('final_content', models.TextField(blank=True, help_text='Contenu final édité par Richard (vide = utilise ai_draft)')),
                ('status', models.CharField(choices=[('pending', 'En attente validation'), ('approved', 'Approuvé (à envoyer)'), ('sent', 'Envoyé'), ('rejected', 'Refusé'), ('expired', 'Expiré'), ('failed', 'Échec envoi')], db_index=True, default='pending', max_length=16)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='ekoalu_pend_status_2d775f_idx'), models.Index(fields=['kind', 'status'], name='ekoalu_pend_kind_7bc839_idx')],
            },
        ),
    ]
