# Generated by Django 5.2.14 on 2026-05-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0002_pendingoutbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingoutbound',
            name='prospect_company',
            field=models.CharField(blank=True, db_index=True, help_text="Nom de l'entreprise extrait du profil (pour validation entreprise)", max_length=255),
        ),
        migrations.AlterField(
            model_name='pendingoutbound',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente validation'), ('approved', 'Approuvé (à envoyer)'), ('sent', 'Envoyé'), ('rejected', 'Refusé'), ('expired', 'Expiré'), ('failed', 'Échec envoi'), ('blocked_company', 'Bloqué (entreprise non validée)')], db_index=True, default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='ApprovedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name_normalized', models.CharField(db_index=True, help_text='Nom en minuscules sans accents — pour matching', max_length=255)),
                ('linkedin_company_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('approved', 'Approuvée (prospection OK)'), ('pending', 'En attente validation'), ('rejected', 'Refusée (blacklist)')], db_index=True, default='pending', max_length=16)),
                ('source', models.CharField(choices=[('manual', 'Ajoutée manuellement par Richard'), ('ai_proposed', "Proposée par l'IA")], default='manual', max_length=16)),
                ('rationale', models.TextField(blank=True, help_text="Pourquoi l'IA propose cette entreprise (si source=ai_proposed)")),
                ('notes', models.TextField(blank=True, help_text='Notes Richard')),
                ('leads_count', models.IntegerField(default=0, help_text='Nombre de prospects identifiés dans cette entreprise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='ekoalu_appr_status_667fc0_idx')],
            },
        ),
    ]
