# Generated by Django 5.2.14 on 2026-05-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0003_pendingoutbound_prospect_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionexample',
            name='explanation',
            field=models.CharField(blank=True, default='', help_text='Note Richard expliquant pourquoi cette correction (aide apprentissage Claude)', max_length=300),
        ),
    ]
