# Generated by Django 5.2.14 on 2026-05-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0004_correctionexample_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaudeUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model', models.CharField(max_length=128)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_creation_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('context', models.CharField(blank=True, db_index=True, help_text="Source de l'appel (qualifier, follow_up, invitation, suggester...)", max_length=64)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'model'], name='ekoalu_clau_timesta_a55a48_idx')],
            },
        ),
    ]
