# Generated by Django 5.2.14 on 2026-05-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0005_claudeusagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_public_id', models.CharField(db_index=True, max_length=128)),
                ('campaign_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('campaign_name', models.CharField(blank=True, default='', max_length=200)),
                ('claude_reason', models.TextField(blank=True, default='', help_text='Raison originale Claude qui a fait disqualifier ce prospect')),
                ('richard_explanation', models.CharField(help_text='Pourquoi Richard contredit / confirme la decision Claude', max_length=500)),
                ('kind', models.CharField(choices=[('requalify', "Remettre en file (Claude s'est trompe)"), ('confirm_reject', 'Confirmer le rejet (Claude a raison)')], default='requalify', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_in_prompt', models.BooleanField(db_index=True, default=False, help_text="True quand l'exemple a ete injecte en few-shot dans le prompt qualifier")),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='ekoalu_qual_kind_6c54d3_idx'), models.Index(fields=['campaign_id', 'kind'], name='ekoalu_qual_campaig_b8e647_idx')],
            },
        ),
    ]
