# Generated by Django 5.2.14 on 2026-05-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0006_qualificationfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificationfeedback',
            name='kind',
            field=models.CharField(choices=[('requalify', "Remettre en file (Claude s'est trompe)"), ('confirm_reject', 'Confirmer le rejet (Claude a raison)'), ('already_connected', 'Deja ma relation (pas un wrong_fit)')], default='requalify', max_length=20),
        ),
    ]
