# Generated by Django 5.2.14 on 2026-05-13 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0007_alter_qualificationfeedback_kind'),
        ('linkedin', '0007_siteconfig_llm_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbmCampaignLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abm_link', to='linkedin.campaign')),
                ('target_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abm_campaigns', to='ekoalu.approvedcompany')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
