# Generated by Django 5.2.14 on 2026-05-20 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0008_abmcampaignlink'),
        ('linkedin', '0007_siteconfig_llm_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctionexample',
            name='instruction',
            field=models.TextField(blank=True, default='', help_text='Consigne textuelle donnee par Richard avant la regeneration (kind=instruction_only|both)'),
        ),
        migrations.AddField(
            model_name='correctionexample',
            name='kind',
            field=models.CharField(choices=[('text_correction', 'Correction texte'), ('instruction_only', 'Consigne seule'), ('both', 'Correction + consigne')], db_index=True, default='text_correction', max_length=20),
        ),
        migrations.CreateModel(
            name='CampaignDmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_booking_in_first_dm', models.BooleanField(default=False, help_text='Si vrai, le 1er DM post-acceptation inclut le lien Outlook Bookings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ekoalu_dm_config', to='linkedin.campaign')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
