# Generated by Django 5.2.14 on 2026-05-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0009_dm_config_and_correction_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnthropicUsageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date UTC')),
                ('model', models.CharField(db_index=True, max_length=128)),
                ('api_key_id', models.CharField(blank=True, default='', help_text='Identifiant cle API Anthropic (ex apikey_abc)', max_length=128)),
                ('workspace_id', models.CharField(blank=True, default='', max_length=128)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('cache_creation_tokens', models.PositiveBigIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveBigIntegerField(default=0)),
                ('cost_usd', models.FloatField(default=0.0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'model'],
                'indexes': [models.Index(fields=['date'], name='ekoalu_anth_date_8de8b2_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'model', 'api_key_id', 'workspace_id'), name='uniq_anthropic_usage_daily')],
            },
        ),
    ]
