# Generated by Django 5.2.14 on 2026-05-22 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0010_anthropicusagedaily'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Ouvert (en cours)'), ('advisory_sent', 'Mail advisory envoye'), ('auto_resolved', 'Resolu automatiquement'), ('escalated', 'Escalade humaine'), ('failed', 'Echec diagnostic')], default='open', max_length=20)),
                ('trigger_health_status', models.CharField(blank=True, max_length=40)),
                ('signature', models.CharField(blank=True, db_index=True, max_length=64)),
                ('diagnosis', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('actions_proposed', models.JSONField(blank=True, default=list)),
                ('cost_usd', models.DecimalField(decimal_places=5, default=0, max_digits=8)),
                ('mail_sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('proposed', 'Propose (advisory)'), ('executed', 'Execute automatiquement'), ('skipped', 'Skip (hors whitelist / preconditions)')], default='proposed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ekoalu.doctorincident')),
            ],
            options={
                'ordering': ['incident', 'created_at'],
            },
        ),
    ]
