# Generated by Django 5.2.14 on 2026-05-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0011_doctorincident_doctoraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingoutbound',
            name='kind',
            field=models.CharField(choices=[('invitation', 'Invitation LinkedIn'), ('follow_up', 'Message follow-up LinkedIn'), ('reply', 'Réponse à un prospect'), ('email_cold', 'Cold mail (1er contact)'), ('email_follow_up', 'Email follow-up')], db_index=True, max_length=16),
        ),
    ]
