# Generated by Django 5.2.14 on 2026-05-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_email_canal_phase1'),
        ('ekoalu', '0012_email_canal_phase1'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingoutbound',
            name='subject',
            field=models.CharField(blank=True, help_text='Objet email (rempli uniquement pour kind=email_*, vide sinon)', max_length=300),
        ),
        migrations.CreateModel(
            name='EmailLeadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=64)),
                ('siren', models.CharField(blank=True, db_index=True, max_length=20)),
                ('entreprise', models.CharField(blank=True, max_length=255)),
                ('dirigeant', models.CharField(blank=True, max_length=255)),
                ('code_naf', models.CharField(blank=True, db_index=True, max_length=10)),
                ('activite', models.CharField(blank=True, max_length=255)),
                ('cp', models.CharField(blank=True, max_length=10)),
                ('dpt', models.CharField(blank=True, db_index=True, max_length=4)),
                ('ville', models.CharField(blank=True, max_length=128)),
                ('effectif_min', models.IntegerField(default=0)),
                ('effectif_max', models.IntegerField(default=0)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_data', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Lead enrichi (canal email)',
                'verbose_name_plural': 'Leads enrichis (canal email)',
            },
        ),
    ]
