# Generated by Django 5.2.14 on 2026-05-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0013_email_lead_data_and_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingreply',
            name='channel',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('email', 'Email')], db_index=True, default='linkedin', max_length=16),
        ),
        migrations.AddField(
            model_name='pendingreply',
            name='inbound_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID Graph du message email entrant (idempotence sur poll)', max_length=200),
        ),
        migrations.AddField(
            model_name='pendingreply',
            name='inbound_subject',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pendingreply',
            name='sender_email',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='pendingreply',
            index=models.Index(fields=['channel', 'status'], name='ekoalu_pend_channel_153aba_idx'),
        ),
    ]
