# Generated by Django 5.2.14 on 2026-05-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0014_email_canal_pending_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingreply',
            name='error_message',
            field=models.TextField(blank=True, default='', help_text='Détail erreur si status=FAILED'),
        ),
        migrations.AlterField(
            model_name='pendingreply',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente validation'), ('approved', 'Approuvé (à envoyer)'), ('sent', 'Envoyé'), ('failed', 'Échec envoi'), ('discarded', 'Abandonné')], default='pending', max_length=16),
        ),
    ]
