# Generated by Django 5.2.14 on 2026-05-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0015_pending_reply_approved_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingoutbound',
            name='prompt_variant',
            field=models.CharField(blank=True, db_index=True, help_text="Variante de prompt Claude utilisée (A/B testing brique H, ex 'v1', 'v2')", max_length=32),
        ),
    ]
