# Generated by Django 5.2.14 on 2026-06-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_deal_outcome'),
        ('ekoalu', '0016_pendingoutbound_prompt_variant'),
        ('linkedin', '0007_siteconfig_llm_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_leads', to='linkedin.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='crm.lead')),
            ],
            options={
                'indexes': [models.Index(fields=['campaign', 'lead'], name='ekoalu_lead_campaig_d9b378_idx')],
                'unique_together': {('lead', 'campaign')},
            },
        ),
    ]
