# Generated by Django 5.2.14 on 2026-07-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0023_correctionexample_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingoutbound',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='Claim atomique APPROVED→SENDING (anti double envoi, LOT D)', null=True),
        ),
        migrations.AddField(
            model_name='pendingreply',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='Claim atomique APPROVED→SENDING (anti double envoi, LOT D)', null=True),
        ),
        migrations.AlterField(
            model_name='pendingoutbound',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente validation'), ('approved', 'Approuvé (à envoyer)'), ('sending', 'Envoi en cours (claim)'), ('sent', 'Envoyé'), ('rejected', 'Refusé'), ('expired', 'Expiré'), ('failed', 'Échec envoi'), ('blocked_company', 'Bloqué (entreprise non validée)')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='pendingreply',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente validation'), ('approved', 'Approuvé (à envoyer)'), ('sending', 'Envoi en cours (claim)'), ('sent', 'Envoyé'), ('failed', 'Échec envoi'), ('discarded', 'Abandonné')], default='pending', max_length=16),
        ),
    ]
