# Generated by Django 5.2.14 on 2026-07-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0026_apifyusageday_failed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricantVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siren', models.CharField(db_index=True, max_length=20, unique=True)),
                ('entreprise', models.CharField(blank=True, max_length=255)),
                ('code_naf', models.CharField(blank=True, max_length=10)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('verdict', models.CharField(choices=[('fabricant', 'Fabricant (atelier propre)'), ('revendeur_poseur', 'Revendeur / poseur'), ('indetermine', 'Indéterminé')], db_index=True, max_length=32)),
                ('confiance', models.CharField(choices=[('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], default='basse', max_length=16)),
                ('materiaux', models.JSONField(blank=True, default=list)),
                ('indices_fabrication', models.JSONField(blank=True, default=list)),
                ('indices_negoce', models.JSONField(blank=True, default=list)),
                ('marques_produits_finis', models.JSONField(blank=True, default=list)),
                ('justification', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=64)),
                ('escalated', models.BooleanField(default=False)),
                ('fetch_error', models.CharField(blank=True, max_length=128)),
                ('pages_fetched', models.JSONField(blank=True, default=list)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Verdict fabricant',
                'verbose_name_plural': 'Verdicts fabricant',
                'ordering': ['-checked_at'],
            },
        ),
    ]
