# Generated by Django 5.2.14 on 2026-08-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0027_fabricantverdict'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProspectionSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('person', 'Personne'), ('company', 'Société')], db_index=True, max_length=16)),
                ('public_identifier', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('siren', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
