# Generated by Django 5.2.14 on 2026-09-02 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_lead_profile_snapshot'),
        ('ekoalu', '0028_prospectionsortie'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrightdataUsageMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Consommation Bright Data (mois)',
                'verbose_name_plural': 'Consommations Bright Data (mois)',
            },
        ),
        migrations.AlterField(
            model_name='pendingreply',
            name='intent',
            field=models.CharField(choices=[('rdv_request', 'RDV_REQUEST'), ('technical_question', 'TECHNICAL_QUESTION'), ('objection', 'OBJECTION'), ('off_topic', 'OFF_TOPIC'), ('opt_out', 'OPT_OUT'), ('wrong_fit', 'WRONG_FIT')], default='off_topic', max_length=32),
        ),
        migrations.CreateModel(
            name='SerpMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('snippet', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serp_meta', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Méta SERP (title/snippet Serper)',
                'verbose_name_plural': 'Métas SERP (title/snippet Serper)',
            },
        ),
    ]
