# Generated by Django 5.2.14 on 2026-09-09 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_lead_profile_snapshot'),
        ('ekoalu', '0029_brightdatausagemonth_alter_pendingreply_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailleaddata',
            name='relation_existante',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingoutbound',
            name='graph_message_id',
            field=models.CharField(blank=True, default='', help_text='Id Graph du message envoyé (Éléments envoyés), pour répondre dans le fil', max_length=300),
        ),
        migrations.AddField(
            model_name='pendingoutbound',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Message d'origine (relance mail → cold mail)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='ekoalu.pendingoutbound'),
        ),
        migrations.CreateModel(
            name='ProspectRdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=300, unique=True)),
                ('prospect_email', models.CharField(blank=True, db_index=True, max_length=254)),
                ('who', models.CharField(blank=True, max_length=255)),
                ('service', models.CharField(blank=True, max_length=128)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('held', 'Tenu'), ('cancelled', 'Annulé')], db_index=True, default='planned', max_length=12)),
                ('channel', models.CharField(blank=True, help_text='email | linkedin | autre', max_length=16)),
                ('cold_variant', models.CharField(blank=True, max_length=32)),
                ('matched_by', models.CharField(blank=True, help_text="email | domain | ''", max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rdvs', to='crm.lead')),
            ],
            options={
                'verbose_name': 'RDV prospect',
                'verbose_name_plural': 'RDV prospects',
            },
        ),
    ]
