# Generated by Django 5.2.14 on 2026-09-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0030_fiches_250_251_252_relance_relation_rdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectrdv',
            name='calendar_event_id',
            field=models.CharField(blank=True, default='', help_text="Id Graph de l'événement Bookings dans l'agenda", max_length=300),
        ),
        migrations.AddField(
            model_name='prospectrdv',
            name='prep_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prospectrdv',
            name='prep_dir',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='prospectrdv',
            name='prep_event_id',
            field=models.CharField(blank=True, default='', help_text='Id Graph du créneau « Prépa » créé 30 min avant', max_length=300),
        ),
        migrations.AddField(
            model_name='prospectrdv',
            name='prep_status',
            field=models.CharField(blank=True, choices=[('', 'À préparer'), ('done', 'Préparé'), ('failed', 'Échec')], db_index=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='prospectrdv',
            name='teams_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='prospectrdv',
            name='matched_by',
            field=models.CharField(blank=True, help_text="email | domain | name | ''", max_length=16),
        ),
    ]
