# Generated by Django 5.2.14 on 2026-09-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekoalu', '0031_prospectrdv_preparation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UndoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sortir_prospect', "Sortie d'un prospect"), ('sortir_societe', "Sortie d'une société"), ('approve', 'Validation'), ('reject', 'Refus'), ('requeue', 'Remise en file'), ('mark_sent', 'Marqué envoyé')], db_index=True, max_length=32)),
                ('label', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
